---
- name: Make sure frr is running
  systemd:
    name: frr.service
    state: started
    enabled: yes
  become: yes
     
- name: Add loopback interface
  nclu:
    commands:
      - add loopback lo ip address {{ rid + '/32' }}

- name: Configure BGP
  nclu:
    commands:
      - add bgp autonomous-system {{ asn }}
      - add bgp router-id {{ rid }}
      - add bgp ipv4 unicast network {{ rid + '/32' }}

- name: Configure BGP Neighbors
  nclu:
    commands:
      - add bgp neighbor {{ item }} interface remote-as external
  loop: "{{ neighbors }}"

- name: Commit changes
  nclu:
    commands:
      - commit
